### PR TITLE
replace UIWebView to WKWebView

### PR DESCRIPTION
**Pull request by sglushchenko**

### CODE REVIEW

**Comment by cproof** [comment]
Dear @sglushchenko ,

can you please take a look specifically at the T&C screen at app launch?
With the library update, the "accept" button now seems missing, also font sizes changed between the versions.
Thank you!

Before merge:
IMG_0228

After merge:
IMG_0227

**Comment by cproof** [comment]
Additionally, it seems that the "Web Page" QoS test was broken by the change.

Screenshot 2020-08-10 at 15 29 41

**Comment by sglushchenko** [comment]
@cproof I have tried to fix these issues. I hope I fix ToC font size. Also, I fixed a status code of the web page in webpage tests, but I can't fix a calculation of the content length, for now, I can't find a solution for it.

New pull request
https://github.com/appscape/open-rmbt-ios/pull/3

**Comment by cproof** [comment]
Thank you @sglushchenko !
Can you please create the Pull Request on this repository (rtr-nettest/open-rmbt-ios)?

**Comment by sglushchenko** [comment]
@cproof Done

**Pull request merged**
