### PR TITLE
Implement new qos section in results screen

### PR DESCRIPTION
**Pull request by sglushchenko**

### CODE REVIEW

**Comment by cproof** [comment]
Thank you!

The parsing and coloring works fine.
Can you please also add the [translation strings](https://github.com/rtr-nettest/open-rmbt-android/blob/fix/rtr_release_fixes/app/src/main/res/values/strings.xml#L200) and the [symbols](https://github.com/rtr-nettest/open-rmbt-android/tree/master/app/src/main/res/drawable)? 
Would it be possible to visualize the percentage (in addition to the color) as in the Android App?

IMG_0232
IMG_0230

**Comment by sglushchenko** [comment]
@cproof Could you provide symbols in png format?
I added translation strings, but it doesn't work for English. How I understand your app doesn't have English localization strings. Should I add English localization too? I can duplicate German localization for quick fix

**Comment by cproof** [comment]
Dear @sglushchenko please find attached the png symbols.
[qoe_png.zip](https://github.com/rtr-nettest/open-rmbt-ios/files/5154821/qoe_png.zip)

On translation: Can you add the translation to the [Resources](https://github.com/rtr-nettest/open-rmbt-ios/tree/master/Resources)? How is it done currently?

**Comment by sglushchenko** [comment]
Hi @cproof. Thanks for your images. But there are very small. Don't worry, I'll convert it from svg.
About Translation. You can see it here, for example for DE version
https://github.com/rtr-nettest/open-rmbt-ios/pull/7/files#diff-ee9eb50203802f76876e5077e5c74e44

**Comment by sglushchenko** [comment]
@cproof Do you like it or need to make some changes?

Simulator Screen Shot - iPhone 8 - 2020-09-03 at 20 29 09

**Comment by cproof** [comment]
Dear @sglushchenko ,

could you please rearrange the "Qualitätstests" to the end of the list and prefix it with the icon? Then it should be consistent with Android:

test_details_android

Otherwise, it looks great!

**Comment by sglushchenko** [comment]
@cproof Could you test it again?

**Comment by cproof** [comment]
Thank you, looks very good!

Some remaining remarks:
* The translations still seem to be missing (orange)
* Could you please move the "QoS" line below the "qos" spacer? (green)
* QoS entries now seem to have random icons. Could you please remove them? (yellow)

grafik

**Comment by sglushchenko** [comment]
@cproof Fixed. I made a quality indicator (for rectangles) similar to another in this section.

Simulator Screen Shot - iPhone 8 - 2020-09-15 at 21 39 43

**Comment by cproof** [comment]
> @cproof Fixed. I made a quality indicator (for rectangles) similar to another in this section. And I skip tap on this QoS item in this QoS section. Because we don't have screen for this item

Thank you, the new ordering looks good!

Minor comments:
* Please change "QoS tests" to "QoS Tests" in the German translation
* Please use the english labels with the values from the Android translation: https://github.com/rtr-nettest/open-rmbt-android/blob/master/app/src/main/res/values/strings.xml#L200

**Comment by sglushchenko** [comment]
@cproof Updated QoS item labels with Android localizations

**Comment by sglushchenko** [comment]
Simulator Screen Shot - iPhone 8 - 2020-09-24 at 17 21 26
Simulator Screen Shot - iPhone 8 - 2020-09-24 at 17 21 19

**Comment by cproof** [comment]
Works perfectly, thank you!

**Pull request merged**
